### ISSUE TITLE
Errors being dumped to the browser!!

### ISSUE THREAD

**Issue by ChrisCarleton** [ChrisCarleton/DiveLog#22]
This gets rendered to the browser when I kill the database on my dev server:
```
Error: connect ECONNREFUSED 127.0.0.1:7777
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
```
Definitely need to handle this more gracefully!!

**Comment by ChrisCarleton** [comment]
Note: I'm fairly certain now that Passport is dumping these to the browser - look into how to catch Passport auth errors and render a proper error message.

**Comment by ChrisCarleton** [comment]
Added some proper error handling middleware to Express. Now a JSON server error response is returned instead.
